name: GitHub Actions Demo
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: check out repo code
        uses: actions/checkout@v3
      - run:  sudo terraform init
      - run:  sudo terraform plan
      - run: sudo terraform apply -auto-approve
        
          ##- name:  configure AWS credentials
          #uses:  aws-actions/configure-aws-credentials@v1
          #with:
          #   aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #   aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # - run:  sudo terraform init
          # - run:  sudo terraform plan
          # - run: sudo terraform apply -auto-approve
