name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: install terraform
        run: sudo apt-get install unzip
      - name: 2
        run: wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
      - name: 3
        run: unzip terraform_1.0.7_linux_amd64.zip
      - name: 4
        run: sudo mv terraform /usr/local/bin/
      - name: 5
        run: terraform --version
      - name: check out repo code
        uses: actions/checkout@v3

          #- name:  configure AWS credentials
          #uses:  aws-actions/configure-aws-credentials@v1
          #with:
          #   aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #   aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # - run:  sudo terraform init
          # - run:  sudo terraform plan
          # - run: sudo terraform apply -auto-approve
